// Generated by CoffeeScript 1.6.1
var app, assets, config, db, express, http, io, mongoose, redis, routes, server, socketio, stylus, url;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

socketio = require('socket.io');

mongoose = require('mongoose');

url = require('url');

http = require('http');

redis = require('redis');

app = express();

server = http.createServer(app);

io = socketio.listen(server);

app.port = process.env.PORT || process.env.VMC_APP_PORT || 8080;

server.listen(process.env.PORT || 8000);

db = redis.createClient();

io.sockets.on("connection", function(socket) {
  console.log('connected');
  socket.on('init', function(req) {
    socket.join(req.wiki);
    if (req.article !== void 0) {
      socket.join(req.article);
    }
    io.sockets.to(req.wiki).emit('connect wiki', io.sockets.clients(req.wiki).length);
    return io.sockets.to(req.article).emit('connect article', io.sockets.clients(req.article).length);
  });
  socket.on("disconnect", function(req) {
    console.log("disconnected");
    socket.leave(req.wiki);
    if (req.article !== void 0) {
      socket.leave(req.article);
    }
    io.sockets.to(req.wiki).emit('disconnect wiki', io.sockets.clients(req.wiki).length - 1);
    return io.sockets.to(req.article).emit('disconnect article', io.sockets.clients(req.article).length - 1);
  });
  socket.on("msg send", function(res) {
    return io.sockets.to(res.article).emit('msg push', res.msg);
  });
  return socket.on("db send", function(res) {
    var json;
    json = {
      "title": res.article,
      "html": res.msg
    };
    return db.hset(res.wiki, res.article, res.msg);
  });
});

config = require("./config");

app.configure('production', 'development', 'testing', function() {
  return config.setEnvironment(app.settings.env);
});

if (app.settings.env !== 'production') {
  mongoose.connect('mongodb://localhost/example');
} else {
  console.log('If you are running in production, you may want to modify the mongoose connect path');
}

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

app.use(express.bodyParser());

routes = require('./routes');

routes(app);

module.exports = app;
