// Generated by CoffeeScript 1.6.1

module.exports = function(app) {
  var db;
  db = require('redis').createClient();
  app.all('/', function(req, res, next) {
    return res.render("index");
  });
  app.all('/:wiki', function(req, res, next) {
    return db.hgetall(req.params.wiki, function(err, reply) {
      if (reply === null) {
        reply = "";
      }
      console.log(reply);
      return res.render("list", {
        wiki: req.params.wiki,
        articles: reply
      });
    });
  });
  app.all('/:wiki/:article', function(req, res, next) {
    return db.hget(req.params.wiki, req.params.article, function(err, reply) {
      return res.render("article", {
        wiki: req.params.wiki,
        article: req.params.article,
        content: reply
      });
    });
  });
  return app.all('/*', function(req, res) {
    console.warn("error 404: ", req.url);
    res.statusCode = 404;
    return res.render('404', 404);
  });
};
